name: "Terraform Deploy"
on:
  push:
    branches-ignore:    
      - '**'
    tags:
      - '**'
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
  GITHUB_BRANCH_NAME: ${{ github.ref_name }}
  AWS_TF_ROLE: ${{ secrets.AWS_TF_ROLE }}
  AWS_PROD_ROLE: ${{ secrets.AWS_PROD_ROLE }}

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .aws/terraform
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Check GIthub Ref
        run: |
          echo ${GITHUB_BRANCH_NAME}

      - name: Set ENV variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}" -backend-config="role_arn=${AWS_TF_ROLE}"

      - name: Terraform Workspaces
        id: workspaces
        env:
          GITHUB_BRANCH_NAME: ${{ github.ref_name }}
        run: |
          chmod +x ../../.github/workflows/utils/workspaces.sh
          source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME

      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -input=false